### ISSUE TITLE
Build Failed in Xcode 7.2.1

### ISSUE THREAD

**Issue by tatsuya-yokoyama** [fulldecent/formant-analyzer#14]
Hello,

I am grateful that I could find this library.
In this project, I have trouble with error.
See below screen capture.

Could you please tell me how to do?

![image](https://cloud.githubusercontent.com/assets/9270368/12969718/0d904ede-d0c8-11e5-8113-36dd7dd2c94b.png)

**Comment by fulldecent** [comment]
This was fixed upstream. We pulled in the working code here 1780b7c7ed4b9dece88efc2a8f78a111daf33778
